server: # REST server
  port: 2334
  address: 0.0.0.0
lavalink:
  server:
    password: "LAVALINK from auth.js"
    ws:
      port: 2333
      host: 0.0.0.0
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    sentryDsn: ""
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 600